name: Kotlin Build

# Trigger the workflow on push or pull request to the master , develop branch
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

# Define the jobs to run
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java (Kotlin runs on the JVM)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21' # JDK version
          distribution: 'temurin'

      # Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Grant execute permission for gradlew (if applicable)
      - name: Make gradlew executable
        run: chmod +x gradlew

      # Build the project using Gradle
      - name: Build with Gradle
        run: ./gradlew build